version: '2'
services:
  aastocks: 
    image: twhtanghk/aastocks
    volumes:
      - ./data:/usr/src/app/data
    env_file: 
      - ./.env

networks:
  default:
    external:
      name: net_default

